package com.trainticket.walletpromotion.application;

import com.trainticket.walletpromotion.domain.*;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

final class EventFactory {
    private EventFactory() {}
    static WalletPromotionEvent issued(PromotionInstrument b, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("issuedAmount", b.issuedAmount()); p.put("availableAmount", b.availableAmount()); p.put("reservedAmount", b.reservedAmount()); p.put("issuanceSource", b.issuanceSource()); p.put("caseId", b.caseId()); p.put("applicableScope", b.applicableScope()); p.put("redemptionRule", b.redemptionRule()); p.put("revocationRule", b.revocationRule()); p.put("validFrom", b.validFrom()); p.put("validUntil", b.validUntil()); p.put("issuedAt", at); return ev("BenefitIssued", b, p, at); }
    static WalletPromotionEvent reserved(PromotionInstrument b, ReserveBenefitCommand c, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("reservedAmount", c.amount()); p.put("reservationRef", c.reservationRef()); p.put("reservationExpiresAt", c.reservationExpiresAt()); p.put("availableAmount", b.availableAmount()); p.put("totalReservedAmount", b.reservedAmount()); p.put("reservedAt", at); return ev("BenefitReserved", b, p, at); }
    static WalletPromotionEvent redeemed(PromotionInstrument b, BenefitRedemption r, String reservationRef, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("redemptionId", r.redemptionId()); p.put("redeemedAmount", r.amount()); p.put("redemptionRef", r.redemptionRef()); p.put("reservationRef", reservationRef); p.put("availableAmount", b.availableAmount()); p.put("reservedAmount", b.reservedAmount()); p.put("totalRedeemedAmount", b.redeemedAmount()); p.put("redeemedAt", at); return ev("BenefitRedeemed", b, p, at); }
    static WalletPromotionEvent released(PromotionInstrument b, ReleaseBenefitCommand c, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("releasedAmount", c.amount()); p.put("reservationRef", c.reservationRef()); p.put("availableAmount", b.availableAmount()); p.put("reservedAmount", b.reservedAmount()); p.put("releasedAt", at); return ev("BenefitReservationReleased", b, p, at); }
    static WalletPromotionEvent expired(PromotionInstrument b, Money amount, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("expiredAmount", amount); p.put("validUntil", b.validUntil()); p.put("availableAmount", b.availableAmount()); p.put("reservedAmount", b.reservedAmount()); p.put("expiredAt", at); return ev("BenefitExpired", b, p, at); }
    static WalletPromotionEvent revoked(PromotionInstrument b, Money amount, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("revokedAmount", amount); p.put("availableAmount", b.availableAmount()); p.put("reservedAmount", b.reservedAmount()); p.put("revokedAt", at); return ev("BenefitRevoked", b, p, at); }
    static WalletPromotionEvent reversed(PromotionInstrument b, String redId, String reversalId, Money amount, WalletBalanceDelta d, Instant at) { Map<String,Object> p = base(b,d); p.put("redemptionId", redId); p.put("reversalId", reversalId); p.put("reversedAmount", amount); p.put("availableAmount", b.availableAmount()); p.put("reservedAmount", b.reservedAmount()); p.put("totalRedeemedAmount", b.redeemedAmount()); p.put("reversedAt", at); return ev("BenefitRedemptionReversed", b, p, at); }
    private static Map<String,Object> base(PromotionInstrument b, WalletBalanceDelta d) { Map<String,Object> p = new LinkedHashMap<>(); p.put("benefitId", b.benefitId()); p.put("accountId", b.accountId()); p.put("walletAccountId", b.walletAccountId()); p.put("benefitType", b.benefitType()); p.put("balanceType", b.balanceType()); p.put("businessReason", b.businessReason()); p.put("walletBalanceDelta", d); p.put("status", b.status()); p.put("aggregateVersion", b.version()); return p; }
    private static WalletPromotionEvent ev(String type, PromotionInstrument b, Map<String,Object> p, Instant at) { p.values().removeIf(java.util.Objects::isNull); return new WalletPromotionEvent(type, p, at, b.version()); }
}
