export {
  createApp,
  health,
  metadata,
  opentelemetryInstrumentationFromEnv,
  type AppOptions,
  type ErrorEnvelope,
  type HealthStatus,
  type InstrumentationHooks,
  type ProbeStatus,
  type RequestContext,
  type RequestTraceContext,
  type ServiceMetadata,
  type TraceResult,
  type TraceSpan,
} from "./app.js";
export { bootstrap, runtimeHost, runtimePort, type BootstrapOptions } from "./bootstrap.js";
export { InMemoryAccountRepository, InMemoryEventPublisher } from "./application.js";
export { InMemoryIdempotencyStore } from "@trainticket/ts-kit";
export type { EventEnvelope, EventPublisher, EventSubscriber, HandlerResult } from "./ports.js";
export {
  DomainError,
  UserAccount,
  Session,
  Preference,
  AccountClosureSaga,
  type AccountCreated,
  type AccountDomainEvent,
  type AccountFrozen,
  type AccountUnfrozen,
  type AccountClosureStarted,
  type AccountClosed,
  type AccountId,
  type AccountStatus,
  type AccountClosureSagaSnapshot,
  type ClosureRequestId,
  type ClosureSagaStatus,
  type CompleteAccountClosure,
  type CreateAccount,
  type FreezeAccount,
  type OpenSession,
  type PreferenceId,
  type PreferenceSnapshot,
  type PreferenceUpdated,
  type RevokeSession,
  type SessionId,
  type SessionOpened,
  type SessionRevoked,
  type SessionSnapshot,
  type SessionStatus,
  type StartAccountClosure,
  type UnfreezeAccount,
  type UpdatePreference,
  type UserAccountSnapshot,
} from "./domain.js";
export { serviceProfile, type ServiceProfile } from "./profile.js";
