package com.trainticket.postsales.domain;

public enum PostSalesStepType {
    DECISION_CONFIRMED,
    HOLD_REPLACEMENT_CAPACITY,
    REQUEST_DIFFERENCE_PAYMENT,
    REQUEST_ASYNC_REFUND,
    VOID_OLD_ENTITLEMENT,
    VOID_ENTITLEMENT,
    CANCEL_SEGMENT,
    RELEASE_CAPACITY,
    ISSUE_NEW_ENTITLEMENT,
    RELEASE_OLD_CAPACITY,
    REQUEST_REFUND,
    APPLY_RESULT
}
