export {
  createApp,
  health,
  metadata,
  opentelemetryInstrumentationFromEnv,
  type ErrorEnvelope,
  type HealthStatus,
  type InstrumentationHooks,
  type ProbeStatus,
  type RequestContext,
  type RequestTraceContext,
  type ServiceMetadata,
  type TraceResult,
  type TraceSpan,
} from "./app.js";
export { bootstrap, runtimeHost, runtimePort, type BootstrapOptions } from "./bootstrap.js";
export { serviceProfile, type ServiceProfile } from "./profile.js";
export {
  DomainError,
  NotificationTask,
  Template,
  RecipientPolicy,
  DeliveryReceipt,
  notificationBoundaryProof,
  idempotencyKey,
  type NotificationTaskId,
  type TemplateId,
  type TemplateCode,
  type RecipientRef,
  type ChannelType,
  type IntentType,
  type EventId,
  type ReceiptId,
  type CausationId,
  type CorrelationId,
  type NotificationTaskStatus,
  type TemplateStatus,
  type DeliveryReceiptOutcome,
  type Money,
  type TemplateVariableSchema,
  type ChannelAdaptation,
  type ChannelPolicyEntry,
  type ScheduleNotification,
  type DispatchNotification,
  type RecordDeliveryReceipt,
  type CancelNotification,
  type RetryNotification,
  type NotificationScheduled,
  type NotificationDispatched,
  type NotificationDelivered,
  type NotificationFailed,
  type NotificationCancelled,
  type NotificationDomainEvent,
  type NotificationTaskSnapshot,
  type TemplateSnapshot,
  type RecipientPolicySnapshot,
  type DeliveryReceiptSnapshot,
  type NotificationBoundaryProof,
} from "./domain.js";
