export {
  createApp,
  health,
  metadata,
  opentelemetryInstrumentationFromEnv,
  type AppOptions,
  type ErrorEnvelope,
  type HealthStatus,
  type InstrumentationHooks,
  type ProbeStatus,
  type RequestContext,
  type RequestTraceContext,
  type ServiceMetadata,
  type TraceResult,
  type TraceSpan,
} from "./app.js";
export { bootstrap, runtimeHost, runtimePort, type BootstrapOptions } from "./bootstrap.js";
export { serviceProfile, type ServiceProfile } from "./profile.js";
export {
  CustomerServiceApplication,
  IdempotencyKeyReusedError,
  IdempotencyStore,
  NotFoundError,
  type AssignSupportCaseRequest,
  type AttachEvidenceRequest,
  type ClassifySupportCaseRequest,
  type CloseCaseRequest,
  type EscalateCaseRequest,
  type OpenSupportCaseRequest,
  type ReopenCaseRequest,
  type ResolveCaseRequest,
  type SupportCaseDetails,
} from "./application/customer-service.js";
export {
  ConsumedEventDeduplicator,
  HandlerError,
  InMemoryEventPublisher,
  InMemoryEventSubscriber,
  PublishFailed,
  SubscribeFailed,
  newCommandId,
  newCorrelationId,
  toEventEnvelope,
  type EventEnvelope,
  type EventPublisher,
  type EventSubscriber,
} from "./application/messaging.js";
export {
  DomainError,
  SupportCase,
  EvidenceRef,
  ManualActionRequest,
  CaseTimeline,
  customerServiceBoundaryProof,
  type SupportCaseId,
  type EvidenceId,
  type ManualActionId,
  type TimelineEntryId,
  type AccountRef,
  type JourneyOrderId,
  type PaymentRef,
  type PostSalesCaseId,
  type RecoveryCaseId,
  type OperatorRef,
  type ApprovalRef,
  type EscalationRef,
  type EventId,
  type CorrelationId,
  type CausationId,
  type SupportCaseStatus,
  type CaseChannel,
  type CasePriority,
  type CaseClassification,
  type ManualActionStatus,
  type ManualActionTargetDomain,
  type EvidenceType,
  type EvidenceAccessLevel,
  type TimelineVisibility,
  type CloseReason,
  type BusinessReferences,
  type Resolution,
  type EscalationInfo,
  type OpenSupportCase,
  type ClassifySupportCase,
  type AssignSupportCase,
  type AttachEvidence,
  type RequestManualAction,
  type RecordActionOutcome,
  type EscalateCase,
  type ResolveCase,
  type CloseCase,
  type ReopenCase,
  type AppendTimelineEntry,
  type SupportCaseOpened,
  type EvidenceAttached,
  type SupportCaseClassified,
  type SupportCaseAssigned,
  type ManualActionRequested,
  type ManualActionResultRecorded,
  type SupportCaseEscalated,
  type SupportCaseResolved,
  type SupportCaseClosed,
  type SupportCaseReopened,
  type CaseTimelineEntryAppended,
  type CustomerServiceDomainEvent,
  type CustomerServiceBoundaryProof,
  type SupportCaseSnapshot,
  type EvidenceRefSnapshot,
  type ManualActionRequestSnapshot,
  type TimelineEntrySnapshot,
  type CaseTimelineSnapshot,
} from "./domain.js";
